import { DistributorConfig } from '../types/catalogue.js'

export const DISTRIBUTOR_CONFIGS: Record<string, DistributorConfig> = {
  COLLECTIVE: {
    name: 'Collective (LP)',
    value: 'COLLECTIVE',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'collective_lp_raw',
    headerRowsToSkip: 9,
    requiresFormatFilter: true,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 4.26,
  },
  SOUTHBOUND: {
    name: 'Southbound',
    value: 'Southbound',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'southbound_instock_raw',
    headerRowsToSkip: 2,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 1.35,
  },
  BORDER: {
    name: 'Border Music',
    value: 'Border Music',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'border_music_raw',
    headerRowsToSkip: 7,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 2.3,
  },
  RHYTHMETHOD: {
    name: 'Rhythmethod',
    value: 'Rhythmethod',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'rhythmethod_group_combined_raw',
    headerRowsToSkip: 9,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 4.52,
  },
  // 🎯 ADDED: Specific handling for Sony/Warner to match frontend strings
  'SONY MUSIC': {
    name: 'Sony Music',
    value: 'Sony Music',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'rhythmethod_group_combined_raw',
    headerRowsToSkip: 9,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 4.52,
  },
  'WARNER MUSIC': {
    name: 'Warner Music',
    value: 'Warner Music',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'rhythmethod_group_combined_raw',
    headerRowsToSkip: 9,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 4.52,
  },
  UNIVERSAL: {
    name: 'Universal Music',
    value: 'UNIVERSAL',
    fileType: 'xlsx',
    accept: '.xlsx',
    rawTableName: 'universal_music_raw',
    headerRowsToSkip: 1,
    origin: 'local',
    currency: 'NZD',
    defaultFreightPerItem: 2.0,
  },
}

export const getDistributorConfig = (val: string) =>
  DISTRIBUTOR_CONFIGS[val.toUpperCase()]
